title: Awheel
subtitle: "A fast, simple & powerful php framework"
description: "Awheel is a fast, simple & powerful php framework"
author: fengqi
language: en
timezone: Asia/Shanghai
url: http://awheel.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:awheel/awheel.github.io.git

disqus_shortname: awheel
twitter: OrgAwheel
github: awheel
